python3 fix: make ListObject parameter order match unit test
ListObject used to set 'offset' and then 'limit', but the unit test assumes that the order is limit=...&offset=.... Since dict and kwargs are guaranteed to preserve insertion order in python3.6+ (https://www.python.org/dev/peps/pep-0468/), this change makes them insert in the same order as the test expects
Fixes
AssertionError: 'http://example.com/foo?offset=0&limit=10' != 'http://example.com/foo?limit=10&offset=0'