python3: fix pickle error in unit test
python3 pickle checks that the __qualname__ does not contain <locals>, so we have to set a fake value in this test
AttributeError: Can't pickle local object 'TestDataObjects.set_up_pickling_class.<locals>.BasicMost'